// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkF8s4m4C5qkzEEpKLbA91seqTudEY9tE',
    appId: '1:263777155260:web:e11da99affc8f592bd38b9',
    messagingSenderId: '263777155260',
    projectId: 'finchat-361e8',
    authDomain: 'finchat-361e8.firebaseapp.com',
    storageBucket: 'finchat-361e8.appspot.com',
    measurementId: 'G-XBDNZQ04YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYiUIiZxtXwjtHqBNt2jsoE8BU6dF1EE',
    appId: '1:263777155260:android:722c86992f5527cbbd38b9',
    messagingSenderId: '263777155260',
    projectId: 'finchat-361e8',
    storageBucket: 'finchat-361e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz_n2H36n32WbZEGgNwKz71qrBPxdgjPY',
    appId: '1:263777155260:ios:736dd79012b05142bd38b9',
    messagingSenderId: '263777155260',
    projectId: 'finchat-361e8',
    storageBucket: 'finchat-361e8.appspot.com',
    iosBundleId: 'com.example.cashSwift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz_n2H36n32WbZEGgNwKz71qrBPxdgjPY',
    appId: '1:263777155260:ios:8cf98d7cfaaab8f9bd38b9',
    messagingSenderId: '263777155260',
    projectId: 'finchat-361e8',
    storageBucket: 'finchat-361e8.appspot.com',
    iosBundleId: 'com.example.cashSwift.RunnerTests',
  );
}
